spring:
  main:
    web-application-type: servlet
  application:
    name: service-consumer

dubbo:
  application:
    name: service-consumer-dubbo
    register-mode: instance
    service-discovery:
      migration: FORCE_APPLICATION
    parameters:
      register-consumer-url: true
    qos-enable: false
    register-consumer: true
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://127.0.0.1:8848
    parameters:
      register-consumer-url: true
server:
  port: 8801