version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:v2.2.2
    container_name: nacos-standalone-mysql
    env_file:
      - ./mysql.env
    ports:
      - "8848:8848"
      - "9848:9848"
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    container_name: mysql
    build:
      context: .
      dockerfile: ./mysql/Dockerfile
    image: example/mysql:8.0.30
    env_file:
      - ./mysql/mysql.env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10

  provider:
    container_name: provider
    image: example/provider:latest
    environment:
      JAVA_OPTS: -Ddubbo.registry.address=nacos://nacos-standalone-mysql:8848 -Ddubbo.metadata-report.report-metadata=false
      DUBBO_REGISTRY_ADDRESS: "nacos://nacos-standalone-mysql:8848"
    ports:
      - "12223:12223"
    depends_on:
      - "nacos"

  consumer:
    container_name: consumer
    image: example/consumer:latest
    environment:
      JAVA_OPTS: -Ddubbo.registry.address=nacos://nacos-standalone-mysql:8848 -Ddubbo.metadata-report.report-metadata=false
      DUBBO_REGISTRY_ADDRESS: "nacos://nacos-standalone-mysql:8848"
    ports:
      - "8801:8801"
    depends_on:
      - "nacos"
      - "provider"